return {
    ["SAu"] = "Trainer Off",
	["SAm"] = "Trainer Off",
	["SAd"] = "Trainer On",
	["SCu"] = "Timer Run",
	["SCm"] = "Timer Reset",
	["SCd"] = "Timer Reset",
	["SDu"] = "Acro Mode",
	["SDm"] = "Acro Mode",
	["SDd"] = "Stable Mode",
	["SEu"] = "Normal",
	["SEm"] = "Idle Up1",
	["SEd"] = "Idle Up2",
	["SFu"] = "Thr Cut",
	["SFd"] = "Thr Active",
	["SGu"] = "Low Rate",
	["SGm"] = "Med Rate",
	["SGd"] = "Hi Rate",
	["SHu"] = "Status",
}